version: "3.0"

services:
  paddle:
    container_name: "cc-paddle-forked"
    image: paddleocr_paddle
    shm_size: "32gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA. Required to avoid "CUDA version: N/A"
                - video # NVENC. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it
    restart: always
    tty: true
    volumes:
      - ./:/app
      - /data:/shared/data
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ports:
      - 5004:5000
    env_file: paddle.env
    networks:
      - proxynet

networks:
  proxynet:
    external:
      name: proxynet
